/**/scale_truck_control_node:
  ros__parameters:    
    subscribers/lane_to_xavier/topic: laneinfo
    subscribers/lane_to_xavier/queue_size: 1
    subscribers/rearlane_to_xavier/topic: rear2xav_msg
    subscribers/rearlane_to_xavier/queue_size: 1
    subscribers/obstacle_reading/topic: min_distance #raw_obstacles min_distance
    subscribers/obstacle_reading/queue_size: 10
    subscribers/lrc_to_xavier/topic: lrc2xav_msg
    subscribers/lrc_to_xavier/queue_size: 1
    subscribers/cmd_to_xavier/topic: /cmd2xav_msg
    subscribers/cmd_to_xavier/queue_size: 10
    subscribers/yolo_to_xavier/topic: yolo_object_detection/Boundingbox
    subscribers/yolo_to_xavier/queue_size: 1
    subscribers/rearyolo_to_xavier/topic: rear_yolo_object_detection/Boundingbox
    subscribers/rearyolo_to_xavier/queue_size: 1
    
    publishers/xavier_to_lane/topic: xav2lane_msg
    publishers/xavier_to_lane/queue_size: 1
    publishers/xavier_to_lrc/topic: xav2lrc_msg
    publishers/xavier_to_lrc/queue_size: 1
    publishers/xavier_to_cmd/topic: DrivingInfo 
    publishers/xavier_to_cmd/queue_size: 10
    publishers/xavier_to_Yolo/topic: run_yolo_flag
    publishers/xavier_to_Yolo/queue_size: 1
    
    #params/index: 2
    params/xav_log_path: /home/avees/ros2_ws/logfiles/

    params/target_vel: 0.00 #km/h
    params/safety_vel: 10.00
    params/fv_max_vel: 190.00
    params/ref_vel: 0.00

    params/target_dist: 18.0
    params/safety_dist: 18.0
    params/lv_stop_dist: 3.0
    params/fv_stop_dist: 3.0

    image_view/enable_console_output: false

