/**:
  ros_parameters:
    subscribers/radar/topic: front_radar
    subscribers/radar/queue_size: 1
    subscribers/BboxArray/topic: yolo_object_detection/BboxArray
    subscribers/BboxArray/queue_size: 1


    publisher/FusingArray/topic: sensor_fusing/FusingArray
    publisher/FusingArray/queue_size: 1
    rgbcam/x : 2.0
    rgbcam/y : 0.0
    rgbcam/z : 3.5
    rgbcam/pitch : -15.0
    rgbcam/yaw : 0.0
    rgbcam/roll : 0.0
    rgbcam/sensor_tick : "0.033333f"
    rgbcam/image_size_x : "640"
    rgbcam/image_size_y : "480"
    rgbcam/fov : "90.0f"
    rgbcam_topic_name : "front_camera"
    radar/x : 2.0
    radar/y : 0.0
    radar/z : 1.5
    radar/pitch : 0.0 
    radar/yaw : 0.0
    radar/roll : 0.0
    radar/sensor_tick : "0.1f"
    radar/horizontal_fov : "40.0f"
    radar/vertical_fov : "30.0f"
    radar/points_per_second : "8000"
    radar/range : "300.0f"
    radar_topic_name: "front_radar" 