/**/LaneDetector:
  ros__parameters:
    subscribers/image_to_lane/topic: front_camera
    subscribers/image_to_lane/queue_size: 1
    subscribers/rearImage_to_lane/topic: null
    subscribers/rearImage_to_lane/queue_size: 1
    subscribers/xavier_to_lane/topic: xav2lane_msg
    subscribers/xavier_to_lane/queue_size: 1

    publishers/lane_to_xavier/topic: laneinfo
    publishers/lane_to_xavier/queue_size: 1

    image_view/enable_opencv: false
    image_view/wait_key_delay: 1

    threshold/box_size: 81  # 51 71 
    threshold/box_offset: 20 # 50 40

    params/angle_degree: 0.0
    params/Kp_d: 2.0
    params/Ki_d: 0.2

    Calibration/f_matrix/a: 300.10805843346054
    Calibration/f_matrix/b: 0.
    Calibration/f_matrix/c: 320.
    Calibration/f_matrix/d: 0.
    Calibration/f_matrix/e: 329.10805843346054
    Calibration/f_matrix/f: 240. 
    Calibration/f_matrix/g: 0.
    Calibration/f_matrix/h: 0.
    Calibration/f_matrix/i: 1.

    Calibration/f_dist_coef/a: -0.34335984453339752
    Calibration/f_dist_coef/b: 0.14676511736197059
    Calibration/f_dist_coef/c: 0.
    Calibration/f_dist_coef/d: 0.
    Calibration/f_dist_coef/e: -0.032260115806245951

    ROI/dynamic_roi: true
    ROI/width: 640
    ROI/height: 480

    ROI/front_cam/width: 640
    ROI/front_cam/height: 480
    ROI/front_cam/top_gap: 0.4 #0.390(11m)
    ROI/front_cam/bot_gap: 0.19  #0.305(11m) 
    ROI/front_cam/top_height: 0.99
    ROI/front_cam/bot_height: 0.51  #0.50 (11m)
    ROI/front_cam/extra_f: 0.00 
    ROI/front_cam/extra_b: 10.00 
    ROI/front_cam/extra_up: 100 #50(11m)
    ROI/front_cam/extra_down: 140

    params/K: 0.15  #vel 0.6,   0.8,  1.0     # FOR ICRA 

    params/a/a: 0.
    params/a/b: -0.37169
    params/a/c: 1.2602
    params/a/d: -1.5161
    params/a/e: 0.70696

    params/b/a: 0.
    params/b/b: -1.7536
    params/b/c: 5.0931
    params/b/d: -4.9047
    params/b/e: 1.6722

    LaneDetector/eL_height: 0.2
    LaneDetector/e1_height: 1.1852 # 1.2563 1.1852
    LaneDetector/trust_height: 0.6667
    LaneDetector/lp: 609.3 # 609.3 472.9
    LaneDetector/steer_angle: 0.0

