/**:
  ros__parameters:    
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "front_cam"
      pixel_format: "yuyv"  
      image_width: 640
      image_height: 480
      camera_name: "front_cam"
     
     
#/**/rear_cam:
#  ros__parameters:    
#      video_device: "/dev/video2"
#      framerate: 30.0
#      io_method: "mmap"
#      frame_id: "usb_cam"
#      pixel_format: "yuyv"  
#      image_width: 640
#      image_height: 480
#      camera_name: "rear_cam"
#      camera_info_url: "package://yolo_object_detection_ros2/config/camera_info.yaml"
#      brightness: -1
#      contrast: -1
#      saturation: -1
#      sharpness: -1
#      gain: -1
#      auto_white_balance: true
#      white_balance: 4000
#      autoexposure: true
#      exposure: 100
#      autofocus: false
#      focus: -1
